apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-persistenceagent
  name: ml-pipeline-persistenceagent
spec:
  selector:
    matchLabels:
      app: ml-pipeline-persistenceagent
  template:
    metadata:
      labels:
        app: ml-pipeline-persistenceagent
    spec:
      containers:
      - env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # If you want a different TTL_SECONDS_AFTER_WORKFLOW_FINISH than the
          # default 1 day, please specify it here as demonstrated below.
          # - name: TTL_SECONDS_AFTER_WORKFLOW_FINISH
          #   value: "172800"
        image: gcr.io/ml-pipeline/persistenceagent:dummy
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-persistenceagent
      serviceAccountName: ml-pipeline-persistenceagent
